name: Tests

on: [ push ]

jobs:
  tests:

    runs-on: ubuntu-20.04

    env:
      php-ini-values: post_max_size=256M
      wp-bp-directory: src/wp-content/plugins/buddypress
      DB_DATABASE: wordpress_test
      DB_USER: root
      DB_PASSWORD: 'root'
      DB_HOST: localhost

    steps:
      - run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE wordpress_test;' -u root -p root
          mysql -e 'SHOW DATABASES;' -uroot -proot
      - name: Cancel previous runs of this workflow
        uses: styfle/cancel-workflow-action@0.6.0
