name: GithubActions

on:
  push:

jobs:
  test:
    name: Ensure Unit Tests Running
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ '3.8' ]
        include:
          - os: ubuntu-20.04
            path: ~/.cache/pip

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: |
          pip install -r requirements/test.txt

      - name: Running tests
        run: |
          . venv/bin/activate
          tox
