name: Tests

on: [ push ]

jobs:
  tests:

    runs-on: ubuntu-20.04

    env:
      MYSQL_ROOT_PASSWORD: password

      steps:
        - name: Setup MySQL
          uses: mirromutth/mysql-action@v1.1
          with:
            mysql root password: $MYSQL_ROOT_PASSWORD

        - name: Wait for MySQL
          run: |
            while ! mysqladmin ping --host=127.0.0.1 --password=$MYSQL_ROOT_PASSWORD --silent; do
              sleep 1
            done